# Generated by Django 5.2.7 on 2025-10-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0004_alter_post_artist_alter_post_created_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='a_posts_pos_created_fc4b3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='a_posts_pos_title_65e1d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='a_posts_pos_artist_f43049_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='a_posts_tag_name_b5130b_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='a_posts_tag_slug_ee3469_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='artist',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
