# Generated by Django 5.2.7 on 2025-11-24 06:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0011_alter_comment_options_rely'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rely',
            new_name='Reply',
        ),
    ]
